<a href="https://colab.research.google.com/github/BBARRY-Lee/Naver-Boost-camp-AI-tech-4th-/blob/main/%EB%B2%A1%ED%84%B0%20%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**벡터 실습해보기**

In [2]:
import numpy as np


In [7]:
x = np.array([1, 7 ,2])
y = np.array([5, 2 ,1])

In [10]:
x + y

array([6, 9, 3])

In [11]:
x - y

array([-4,  5,  1])

In [12]:
x * y

array([ 5, 14,  2])

In [17]:
# L2-노름 : 피타고라스 정리를 이용해 유클리드 거리를 계산
# L2-노름은 np.linalg.norm을 이용해도 구현가능
def l1_norm(x):
  x_norm = np.abs(x)
  x_norm = np.sum(x_norm)
  return x_norm

def l2_norm(x):
  x_norm =x*x
  x_norm = np.sum(x_norm)
  x_norm = np.sqrt(x_norm)
  return x_norm

In [20]:
# 내적을 np.inner을 이용해 계산
def angle(x, y):
  v= np.inner(x, y) / (l2_norm(x) * l2_norm(y))
  theta = np.arccos(v)
  return theta